export function createHTML(){
    var uniqueValues = [];
    excelColumns = [];
    for(var key in spendingItems[0]){
      for(var i = 0; i<spendingItems.length; i++){
        if(uniqueValues.indexOf(spendingItems[i][`${key}`]) === -1){
          uniqueValues.push(spendingItems[i][`${key}`]);
        }
      }
      if(key !== 'date' && key !== 'amount' && key !== 'weather' && key !== 'description'){
        makeSelection(key, uniqueValues, "autoGenerated");
        excelColumns.push(key);
      }
      uniqueValues = [];
    }
    makeSelection("columns", excelColumns, "columnFilters");
}

function makeSelection(input, optionList, divId){
  var myDiv = document.getElementById(divId);
  var newLabel = document.createElement("label");
  var newSelection = document.createElement("select");
  
  newLabel.textContent = input;
  newSelection.id = input + "Selection";
  
  myDiv.appendChild(newLabel);
  myDiv.appendChild(newSelection);

  optionList.forEach(opt => {
      var option = document.createElement("option");
      option.text = opt;
      option.value = opt;
      newSelection.appendChild(option);
  });
}