//#region selections filters innnerHtml
function createHTML(){
    var uniqueValues = [];
    excelColumns = [];
    for(var key in spendingItems[0]){
      for(var i = 0; i<spendingItems.length; i++){
        if(uniqueValues.indexOf(spendingItems[i][`${key}`]) === -1){
          uniqueValues.push(spendingItems[i][`${key}`]);
        }
      }
      if(key !== 'date' && key !== 'amount' && key !== 'weather' && key !== 'description'){
        makeSelection(key, uniqueValues, "autoGenerated");
        excelColumns.push(key);
      }
      uniqueValues = [];
    }
    makeSelection("columns", excelColumns, "columnFilters");
}

function makeSelection(input, optionList, divId){
  var myDiv = document.getElementById(divId);
  var newLabel = document.createElement("label");
  var newSelection = document.createElement("select");
  
  newLabel.textContent = input;
  newSelection.id = input + "Selection";
  
  myDiv.appendChild(newLabel);
  myDiv.appendChild(newSelection);

  optionList.forEach(opt => {
      var option = document.createElement("option");
      option.text = opt;
      option.value = opt;
      newSelection.appendChild(option);
  });
}
//#endregion

//#region total-cost-to-inner-html
function TotalCost(amountList){
    var sum = amountList.reduce((a,b) => a + b, 0).toFixed(2); //sum
  
    if(amountList.length > 0){ //average
      var average = sum/amountList.length;
    }else{
      var average = 0;
    }
  
    $('#totalCost').empty(); //clean the previous if exists!
    var myDiv = document.getElementById("totalCost");
    var h2Total = document.createElement("h2");
    h2Total.textContent = "Total cost: " + sum.toString();
    myDiv.appendChild(h2Total);
    myDiv.appendChild(document.createElement("br"));
    var h2Average = document.createElement("h2");
    h2Average.textContent = "Average: " + average.toString();
    myDiv.appendChild(h2Average);
  }
  //#endregion